'use strict';
const $=id=>document.getElementById(id);
const KEY='jarvis2_data';
const defaults={history:[],memory:'',personality:'elegante',endpoint:'',voice:true};
let state;
try{const saved=JSON.parse(localStorage.getItem(KEY)||'{}');state={...defaults,...saved};if(!Array.isArray(state.history))state.history=[];}catch{state={...defaults};}
const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(state));}catch{setStatus('Almacenamiento no disponible');}};
function setStatus(s){$('status').textContent='● '+s;}
function add(role,text,save=true){const node=document.createElement('div');node.className='msg '+(role==='TÚ'?'user':'assistant');const who=document.createElement('div');who.className='who';who.textContent=role;const body=document.createElement('div');body.textContent=text;node.append(who,body);$('chat').append(node);$('chat').scrollTop=$('chat').scrollHeight;if(save){state.history.push({role,text:String(text).slice(0,6000)});state.history=state.history.slice(-40);persist();}}
function speak(text){if(!state.voice||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.slice(0,600));u.lang='es-PE';u.rate=.97;const voices=speechSynthesis.getVoices();const preferred=voices.find(v=>/^es(-|_)/i.test(v.lang)&&/lat|mex|per|col|us/i.test(v.lang))||voices.find(v=>/^es/i.test(v.lang));if(preferred)u.voice=preferred;speechSynthesis.speak(u);}
function localReply(raw){const q=raw.toLocaleLowerCase('es').trim();let url=null;let reply;
if(/^(hola|buenos días|buenas tardes|buenas noches)/.test(q))reply='A sus órdenes. Soy JARVIS. Todos los sistemas locales están listos.';
else if(/\b(hora|qué horas)\b/.test(q))reply='Son las '+new Intl.DateTimeFormat('es-PE',{hour:'2-digit',minute:'2-digit'}).format(new Date())+'.';
else if(/\b(fecha|qué día|dia de hoy)\b/.test(q))reply='Hoy es '+new Intl.DateTimeFormat('es-PE',{dateStyle:'full'}).format(new Date())+'.';
else if(/^(recuerda que|recuerda:)/.test(q)){const detail=raw.replace(/^(recuerda que|recuerda:)\s*/i,'').trim();if(detail){state.memory=(state.memory+'\n'+detail).trim().slice(-3500);$('memory').value=state.memory;persist();reply='He guardado esa información en la memoria local de este dispositivo.';}else reply='Dime qué deseas que recuerde.';}
else if(/(qué recuerdas|que recuerdas|mi memoria)/.test(q))reply=state.memory?'Esto tengo guardado:\n'+state.memory:'Aún no tengo recuerdos guardados.';
else if(/abre youtube/.test(q)){reply='Abriendo YouTube.';url='https://www.youtube.com/';}
else if(/abre google/.test(q)){reply='Abriendo Google.';url='https://www.google.com/';}
else if(/^(busca|buscar)\s+/.test(q)){const term=raw.replace(/^(busca|buscar)\s+/i,'').trim();reply='Preparé una búsqueda de '+term+'.';url='https://www.google.com/search?q='+encodeURIComponent(term);}
else if(/ayuda|qué puedes hacer/.test(q))reply='Puedo responder comandos locales, hablar, escuchar si tu navegador lo permite, recordar notas y realizar búsquedas. Para conversar con IA avanzada debes conectar un servidor seguro.';
else reply=state.personality==='formal'?'No dispongo de una respuesta local para esa consulta. Para preguntas abiertas, configura un servidor de inteligencia artificial.':state.personality==='amistoso'?'Todavía no sé responder eso sin IA externa. Podemos activar una conexión segura en Configuración.':'Esa consulta excede mis rutinas locales. Un cerebro de IA conectado sería conveniente, si me permite la observación.';
return {reply,url};}
async function askAI(text){const url=state.endpoint.trim();if(!/^https:\/\//i.test(url))throw new Error('La dirección del servidor debe comenzar con https://');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),25000);try{const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,memory:state.memory,personality:state.personality,history:state.history.slice(-12)}),signal:controller.signal});if(!res.ok)throw new Error('El servidor respondió '+res.status);const data=await res.json();if(typeof data.reply!=='string'||!data.reply.trim())throw new Error('Respuesta inválida del servidor');return data.reply.slice(0,6000);}finally{clearTimeout(timer);}}
let busy=false;
async function submit(text){text=text.trim();if(!text||busy)return;add('TÚ',text);busy=true;$('send').disabled=true;setStatus('PROCESANDO');try{let answer,url;if(state.endpoint){answer=await askAI(text);}else{({reply:answer,url}=localReply(text));}add('JARVIS',answer);speak(answer);if(url){const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Abrir enlace';a.style.color='#6ce6ff';const wrap=document.createElement('div');wrap.className='msg assistant';wrap.append(a);$('chat').append(wrap);}}catch(e){add('JARVIS','No pude conectar con la IA: '+e.message+'. Puedes borrar la URL en Configuración para volver al modo local.');}finally{busy=false;$('send').disabled=false;setStatus('EN ESPERA');}}
$('form').addEventListener('submit',e=>{e.preventDefault();const t=$('message').value;$('message').value='';submit(t);});
$('personality').value=state.personality;$('memory').value=state.memory;$('endpoint').value=state.endpoint;
$('personality').addEventListener('change',e=>{state.personality=e.target.value;persist();});
$('saveMemory').addEventListener('click',()=>{state.memory=$('memory').value.slice(0,3500);persist();add('JARVIS','Memoria local guardada.');});
function refreshMode(){$('mode').textContent=state.endpoint?'IA EXTERNA CONFIGURADA':'MODO LOCAL';}
$('saveEndpoint').addEventListener('click',()=>{const u=$('endpoint').value.trim();if(u&&!/^https:\/\//i.test(u)){add('JARVIS','Solo se permiten conexiones HTTPS.');return;}state.endpoint=u;persist();refreshMode();add('JARVIS',u?'Dirección guardada. Verifica que tu servidor admita POST JSON y CORS.':'Modo local activado.');});
$('sound').addEventListener('click',()=>{state.voice=!state.voice;persist();$('sound').textContent=state.voice?'🔊 Voz':'🔇 Silencio';$('sound').setAttribute('aria-pressed',String(state.voice));if(!state.voice&&'speechSynthesis'in window)speechSynthesis.cancel();});
$('sound').textContent=state.voice?'🔊 Voz':'🔇 Silencio';$('sound').setAttribute('aria-pressed',String(state.voice));
$('clear').addEventListener('click',()=>{if(!confirm('¿Borrar el historial de conversación?'))return;state.history=[];persist();$('chat').replaceChildren();add('JARVIS','Historial eliminado. Tu memoria guardada sigue intacta.',false);});
$('erase').addEventListener('click',()=>{if(!confirm('¿Eliminar historial, memoria y configuración de este dispositivo?'))return;state={...defaults};persist();location.reload();});
$('export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({history:state.history,memory:state.memory,personality:state.personality},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download='jarvis-mis-datos.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){$('mic').disabled=true;$('mic').textContent='🎙 No disponible';}else{$('mic').addEventListener('click',()=>{try{const rec=new Recognition();rec.lang='es-PE';rec.interimResults=false;rec.onstart=()=>setStatus('ESCUCHANDO');rec.onend=()=>setStatus('EN ESPERA');rec.onerror=()=>add('JARVIS','No se pudo reconocer la voz. Revisa los permisos del micrófono.',false);rec.onresult=e=>submit(e.results[0][0].transcript);rec.start();}catch{add('JARVIS','No se pudo iniciar el micrófono.',false);}});}
refreshMode();if(state.history.length){for(const item of state.history)add(item.role,item.text,false);}else add('JARVIS','Bienvenido. Soy JARVIS 2.0. Puedes hablarme, guardar recuerdos y configurar mi personalidad. Por ahora estoy en modo local.',false);
if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
